More codelist validation
statisticsnorway/microdata-tools pull request #32
Opened 2023-11-28 14:55 UTC by DanielElisenberg

* Added extra testing for codelists to ensure that no duplicate code definitions overlap each other in the same time span
* Added tests for unit_type_variables where they are fully tested in the context of a generated metadata file (including the new code list checks)
* Updated metadata code list errors for KOMMUNE. I would like it if you could take a look at the changes in KOMMUNE.json @JohanSjoberg99

2023-11-28 15:58 UTC, JohanSjoberg99 requested changes
Keep 5412 - Dielddanuorri - Tjeldsund, remove 4512 - Tjeldsund.
Will check if "ukjent komune" or just "kommune

2023-11-28 15:58 UTC, JohanSjoberg99 commented on microdata_tools/validation/components/unit_type_variables/KOMMUNE.json
> -      },
According to KLASS. This is the correct one: 5412 - Dielddanuorri - Tjeldsund. @DanielElisenberg

2023-11-28 15:58 UTC, JohanSjoberg99 commented on microdata_tools/validation/components/unit_type_variables/KOMMUNE.json
> -      },
Will check to see if we should keep "ukjent kommune i Svalbard" and delete the other one.

2023-11-29 10:52 UTC, pawbu approved these changes
Well done!

2023-11-29 11:15 UTC, JohanSjoberg99 approved these changes
All changes is according to agreement.

2023-11-29 11:21 UTC, pawbu approved these changes
💯

2023-11-29 11:24 UTC, merged